// app/privacidad/page.tsx
// Política de Privacidad de la plataforma Vanty (nivel plataforma, multi-centro).
// Bilingüe (ES/EN): el idioma se toma de la cookie `vanty_locale` que fija el middleware.

import { cookies } from 'next/headers'
import LegalPage, { Lista, Destacado, type SeccionLegal } from '@/components/legal/LegalPage'
import {
  Building2, Database, Target, Scale, Share2, ShieldCheck, Sparkles, Baby, UserCheck, LogIn, Archive,
  RefreshCw, Mail, KeyRound, Lock, ServerCog, BadgeCheck, Ban, Trash2,
} from 'lucide-react'
import { PLATFORM_NAME } from '@/lib/branding'
import { localeServidor, metadatosPagina } from '@/lib/seo'

export async function generateMetadata() {
  const en = (await localeServidor()) === 'en'
  return metadatosPagina(en
    ? { ruta: '/privacidad', en, title: `Privacy Policy · ${P}`, description: `How ${P} protects the personal and clinical data of the families served by the centers that use the platform.` }
    : { ruta: '/privacidad', en, title: `Política de Privacidad · ${P}`, description: `Cómo ${P} protege los datos personales y clínicos de las familias atendidas en los centros que usan la plataforma.` })
}

// Nombre comercial completo de la plataforma en los documentos legales
const P = `${PLATFORM_NAME} ABA`

function secciones(en: boolean): SeccionLegal[] {
  const L = (e: string, s: string) => (en ? e : s)
  return [
    {
      id: 'identidad', Icon: Building2, title: L('Who we are and scope', 'Quiénes somos y alcance'),
      body: <>
        <p>{L(`${P} is a clinical-management platform for child development and therapy centers (ABA, ASD, ADHD and related areas). It enables each center to manage its patients' clinical records and to communicate securely with families.`,
          `${P} es una plataforma de gestión clínica para centros de desarrollo infantil y terapia (ABA, TEA, TDAH y áreas afines). Permite a cada centro gestionar la información clínica de sus pacientes y comunicarse de forma segura con las familias.`)}</p>
        <p>{L(`Each center that uses ${P} acts as the data controller for the information of its patients and families. ${P} acts as the data processor: it processes that information on the center's behalf, following its instructions and solely to provide the service.`,
          `Cada centro que utiliza ${P} actúa como responsable del tratamiento de los datos de sus pacientes y familias. ${P} actúa como encargado del tratamiento: procesa dicha información por cuenta del centro, siguiendo sus instrucciones y únicamente para prestar el servicio.`)}</p>
      </>,
    },
    {
      id: 'datos', Icon: Database, title: L('Information we process', 'Información que tratamos'),
      body: <>
        <p>{L('We process only the information necessary to provide the service:', 'Tratamos únicamente la información necesaria para prestar el servicio:')}</p>
        <Lista items={[
          [L('Account data:', 'Datos de cuenta:'), L('full name, email address, phone number and, optionally, a profile photo.', 'nombre completo, correo electrónico, teléfono y, de forma opcional, fotografía de perfil.')],
          [L('Patient data:', 'Datos del paciente:'), L('name, date of birth, diagnosis, assessments, therapy programs, session records and progress. This is sensitive health data and receives reinforced protection.', 'nombre, fecha de nacimiento, diagnóstico, evaluaciones, programas terapéuticos, registros de sesión y progreso. Se trata de datos sensibles de salud y reciben protección reforzada.')],
          [L('Content you share:', 'Contenido que compartes:'), L('forms, messages, audio, images and documents exchanged with the center.', 'formularios, mensajes, audios, imágenes y documentos intercambiados con el centro.')],
          [L('AI queries:', 'Consultas a la IA:'), L('questions asked to ARIA and the content generated by the AI features, only if the center (and, for families, each account) has turned them on.', 'preguntas hechas a ARIA y el contenido generado por las funciones de IA, solo si el centro (y, en el caso de las familias, cada cuenta) las activó.')],
          [L('Technical data:', 'Datos técnicos:'), L('connection and access logs, kept for a limited time for security purposes.', 'registros de conexión y acceso, conservados por un tiempo limitado con fines de seguridad.')],
        ]} />
      </>,
    },
    {
      id: 'finalidades', Icon: Target, title: L('Purposes of processing', 'Finalidades del tratamiento'),
      body: <>
        <Lista items={[
          [L('Clinical care:', 'Atención clínica:'), L('managing the clinical record and therapeutic follow-up of the patient.', 'gestionar la historia clínica y el seguimiento terapéutico del paciente.')],
          [L('Reports:', 'Reportes:'), L('preparing progress reports for families and professionals.', 'elaborar informes de progreso para familias y profesionales.')],
          [L('Communication:', 'Comunicación:'), L('sending appointment notices, reminders and messages from the center.', 'enviar avisos de citas, recordatorios y comunicaciones del centro.')],
          [L('Security and continuity:', 'Seguridad y continuidad:'), L('protecting accounts, preventing misuse and keeping the service running.', 'proteger las cuentas, prevenir usos indebidos y mantener el servicio operativo.')],
        ]} />
        <Destacado>{L('Your data is never used for advertising, profiling for commercial purposes, or sold to third parties.', 'Tus datos nunca se utilizan con fines publicitarios, para elaborar perfiles comerciales ni se venden a terceros.')}</Destacado>
      </>,
    },
    {
      id: 'base-legal', Icon: Scale, title: L('Legal basis', 'Base legal'),
      body: <p>{L('Processing is based on the consent of the data subject or, in the case of minors, of their parent or legal guardian; on the performance of the health service requested from the center; and on compliance with the legal obligations applicable to clinical records.',
        'El tratamiento se basa en el consentimiento del titular o, tratándose de menores de edad, de su padre, madre o tutor legal; en la ejecución del servicio de salud solicitado al centro; y en el cumplimiento de las obligaciones legales aplicables a los registros clínicos.')}</p>,
    },
    {
      id: 'destinatarios', Icon: Share2, title: L('Recipients and service providers', 'Destinatarios y proveedores'),
      body: <>
        <p>{L('Information is only accessible to:', 'La información solo es accesible por:')}</p>
        <Lista items={[
          [L('The center\'s clinical team', 'El equipo clínico del centro'), L('directly involved in the patient\'s care, according to their role.', 'directamente involucrado en la atención del paciente, según su rol.')],
          [L('Competent authorities,', 'Autoridades competentes,'), L('exclusively when required by law or court order.', 'exclusivamente cuando lo exija la ley o un mandato judicial.')],
        ]} />
        <p className="mt-3">{L('To provide the service we rely on these providers (sub-processors), who only process data on our behalf, under confidentiality and security obligations, and never for their own purposes:',
          'Para prestar el servicio nos apoyamos en estos proveedores (subencargados), que solo tratan los datos por nuestra cuenta, con obligaciones de confidencialidad y seguridad, y nunca para fines propios:')}</p>
        <Lista items={[
          ['Supabase Inc.:', L('database, sign-in and file storage. Servers in São Paulo, Brazil.', 'base de datos, inicio de sesión y almacenamiento de archivos. Servidores en São Paulo, Brasil.')],
          ['Vercel Inc.:', L('hosting of the web application (United States, global network).', 'alojamiento de la aplicación web (Estados Unidos, red global).')],
          ['Groq, Inc.:', L('artificial intelligence: ARIA, automatic reports, analyses, document reading and translations (United States). Only if the center turns on AI features; see the section on artificial intelligence.', 'inteligencia artificial: ARIA, informes automáticos, análisis, lectura de documentos y traducciones (Estados Unidos). Solo si el centro activa las funciones de IA; ver la sección de inteligencia artificial.')],
          [L('Tavily and OpenAlex:', 'Tavily y OpenAlex:'), L('internet and academic-article search when ARIA looks up recent evidence (United States). They only receive the general question, never the patient\'s name or clinical data.', 'búsqueda en internet y en artículos académicos cuando ARIA consulta evidencia reciente (Estados Unidos). Solo reciben la pregunta general, nunca el nombre ni los datos clínicos del paciente.')],
          ['DeepInfra, Inc.:', L('backup artificial intelligence provider (United States): it only receives requests when Groq is unavailable, with the same models and the same conditions.', 'proveedor de inteligencia artificial de respaldo (Estados Unidos): solo recibe consultas cuando Groq no está disponible, con los mismos modelos y las mismas condiciones.')],
          ['Google LLC (Gmail):', L('sending of emails: account confirmation, notices, invitations and receipts (United States).', 'envío de correos: confirmación de cuenta, avisos, invitaciones y recibos (Estados Unidos).')],
          [L('Google Calendar and Microsoft Outlook:', 'Google Calendar y Microsoft Outlook:'), L('only if you link your calendar, to create your appointment events (United States).', 'solo si vinculas tu calendario, para crear los eventos de tus citas (Estados Unidos).')],
          ['Lemon Squeezy LLC:', L('payment of the centers\' subscriptions, as merchant of record (United States). It receives billing data of the center, never clinical data.', 'cobro de las suscripciones de los centros, como comerciante registrado (Estados Unidos). Recibe datos de facturación del centro, nunca datos clínicos.')],
        ]} />
        <p className="mt-3">{L('Because these providers host data outside Peru, cross-border data flows are carried out with appropriate safeguards, in accordance with applicable regulations.', 'Como estos proveedores alojan datos fuera del Perú, el flujo transfronterizo se realiza con garantías adecuadas, conforme a la normativa aplicable.')}</p>
      </>,
    },
    {
      id: 'seguridad', Icon: ShieldCheck, title: L('Information security', 'Seguridad de la información'),
      body: <>
        <p>{L('We apply technical and organizational measures proportional to the sensitivity of the data:', 'Aplicamos medidas técnicas y organizativas proporcionales a la sensibilidad de los datos:')}</p>
        <Lista items={[
          [L('Encryption at rest', 'Cifrado en reposo'), L('with AES-256.', 'con AES-256.')],
          [L('Encryption in transit', 'Cifrado en tránsito'), L('through TLS connections on every communication.', 'mediante conexiones TLS en todas las comunicaciones.')],
          [L('Isolation by center:', 'Aislamiento por centro:'), L('row-level security policies (Row Level Security) ensure each center only accesses its own records.', 'políticas de seguridad a nivel de fila (Row Level Security) garantizan que cada centro acceda únicamente a sus propios registros.')],
          [L('Role-based access', 'Acceso por roles'), L('(director, administrator, specialist, therapist, secretary, family), following the principle of least privilege.', '(dirección, administración, especialista, terapeuta, secretaría, familia), bajo el principio de mínimo privilegio.')],
          [L('Optional two-step verification', 'Verificación en dos pasos opcional'), L('for every account.', 'para todas las cuentas.')],
        ]} />
      </>,
    },
    {
      id: 'ia', Icon: Sparkles, title: L('Responsible use of artificial intelligence', 'Uso responsable de la inteligencia artificial'),
      body: <>
        <p>{L('ARIA (the platform\'s assistant), automatic reports, analyses, document reading and translations use language models provided by Groq, Inc. and, only as a backup when Groq is unavailable, by DeepInfra, Inc. (both in the United States). Their use follows these principles:',
          'ARIA (el asistente de la plataforma), los informes automáticos, los análisis, la lectura de documentos y las traducciones usan modelos de lenguaje del proveedor Groq, Inc. y, solo como respaldo cuando Groq no está disponible, de DeepInfra, Inc. (ambos en Estados Unidos). Su uso se rige por los siguientes principios:')}</p>
        <Lista items={[
          [L('Prior consent:', 'Consentimiento previo:'), L('AI features stay off until the center\'s director authorizes them, after being told which provider receives the data. Each family also authorizes ARIA for their own account. Nothing is sent to the provider without that permission.', 'las funciones de IA permanecen desactivadas hasta que la dirección del centro las autoriza, tras ser informada de qué proveedor recibe los datos. Cada familia autoriza además ARIA para su propia cuenta. Sin ese permiso no se envía nada al proveedor.')],
          [L('Data minimization:', 'Minimización:'), L('only the context strictly necessary for each request is sent (for example, the patient\'s programs and session data needed for a report).', 'se envía únicamente el contexto estrictamente necesario para cada consulta (por ejemplo, los programas y datos de sesión del paciente que requiere un informe).')],
          [L('No training:', 'Sin entrenamiento:'), L('the provider does not use this information to train artificial intelligence models, nor for any purpose other than generating the response.', 'el proveedor no usa esta información para entrenar modelos de inteligencia artificial ni para otro fin que generar la respuesta.')],
          [L('Zero data retention:', 'Retención cero:'), L('our account with Groq has zero data retention enabled, and DeepInfra does not store the requests sent to its API: the requests and the responses are not stored or logged; they are only processed to generate each response.', 'nuestra cuenta con Groq tiene activada la retención cero de datos y DeepInfra no almacena las consultas que recibe por su API: las consultas y las respuestas no se guardan ni se registran; solo se procesan para generar cada respuesta.')],
          [L('You can turn it off:', 'Puedes desactivarla:'), L('the center in Settings → Center, and each family in their Profile. Without AI, the rest of the platform works the same.', 'el centro en Configuración → Centro, y cada familia en su Perfil. Sin IA, el resto de la plataforma funciona igual.')],
          [L('Human oversight:', 'Supervisión humana:'), L('AI is a support tool; it does not issue diagnoses or replace the professional judgment of the therapy team.', 'la IA es una herramienta de apoyo; no emite diagnósticos ni sustituye el criterio profesional del equipo terapéutico.')],
        ]} />
      </>,
    },
    {
      id: 'menores', Icon: Baby, title: L('Protection of minors', 'Protección de menores de edad'),
      body: <>
        <p>{L('Minors\' data is processed with the consent of their parent or legal guardian and with the highest level of confidentiality:', 'Los datos de menores de edad se tratan con el consentimiento de su padre, madre o tutor legal y con el más alto nivel de confidencialidad:')}</p>
        <Lista items={[
          [L('Restricted access:', 'Acceso restringido:'), L('only the responsible parent or guardian and the professionals assigned to the case.', 'solo el padre, madre o tutor responsable y los profesionales asignados al caso.')],
          [L('No commercial use:', 'Sin uso comercial:'), L('the minor\'s data is never used for advertising or marketing profiles.', 'los datos del menor nunca se utilizan para publicidad ni perfiles de marketing.')],
          [L('Control for the guardian:', 'Control del tutor:'), L('they may exercise the minor\'s rights at any time.', 'puede ejercer en cualquier momento los derechos del menor.')],
        ]} />
      </>,
    },
    {
      id: 'derechos', Icon: UserCheck, title: L('Your rights', 'Tus derechos'),
      body: <>
        <p>{L('Under Peru\'s Personal Data Protection Law (Law No. 29733) and its regulations, you may exercise free of charge the rights of:', 'Conforme a la Ley de Protección de Datos Personales (Ley N.º 29733) y su reglamento, puedes ejercer de forma gratuita los derechos de:')}</p>
        <div className="mt-3 grid gap-2 sm:grid-cols-[repeat(2,minmax(0,1fr))]">
          {[
            [L('Access', 'Acceso'), L('Know which data we process, for what purpose and for how long.', 'Conocer qué datos tratamos, con qué finalidad y por cuánto tiempo.')],
            [L('Rectification', 'Rectificación'), L('Correct data that is inaccurate, outdated or incomplete.', 'Corregir datos inexactos, desactualizados o incompletos.')],
            [L('Erasure', 'Cancelación'), L('Request deletion, subject to legal clinical-record retention obligations.', 'Solicitar su supresión, sujeta a las obligaciones legales de conservación clínica.')],
            [L('Objection', 'Oposición'), L('Object to processing for specific purposes.', 'Oponerte al tratamiento para finalidades concretas.')],
            [L('Information', 'Información'), L('Be informed about the conditions of processing.', 'Ser informado sobre las condiciones del tratamiento.')],
            [L('Portability', 'Portabilidad'), L('Receive a copy of your information in a structured format.', 'Recibir una copia de tu información en un formato estructurado.')],
          ].map(([t, d]) => (
            <div key={t} className="rounded-v-sm border border-v-border bg-v-bg p-3.5">
              <p className="text-sm font-semibold text-v-text">{t}</p>
              <p className="mt-0.5 text-[13px] leading-snug">{d}</p>
            </div>
          ))}
        </div>
        <p className="mt-4">{L('Requests are submitted to the center that provides your care, which is the data controller; the platform assists it in responding within the legal deadlines. If you consider your request was not properly addressed, you may file a claim with the National Authority for Personal Data Protection (Ministry of Justice and Human Rights of Peru).',
          'Las solicitudes se presentan ante el centro que te atiende, como responsable del tratamiento; la plataforma le presta el apoyo necesario para responder dentro de los plazos legales. Si consideras que tu solicitud no fue debidamente atendida, puedes presentar un reclamo ante la Autoridad Nacional de Protección de Datos Personales del Ministerio de Justicia y Derechos Humanos.')}</p>
      </>,
    },
    {
      id: 'eliminar', Icon: Trash2, title: L('How to delete your data', 'Cómo eliminar tus datos'),
      body: <>
        <Lista items={[
          [L('Families and team members:', 'Familias y miembros del equipo:'), L('ask the center that provides your care, or write to vantysupport@gmail.com from the email of your account. We delete your account and your data within 10 business days, except the clinical record that the center must keep by law.', 'pídelo al centro que te atiende, o escribe a vantysupport@gmail.com desde el correo de tu cuenta. Eliminamos tu cuenta y tus datos en un plazo de 10 días hábiles, salvo la historia clínica que el centro debe conservar por ley.')],
          [L('Centers:', 'Centros:'), L('the director may request the closure of the center. All its data is deleted: patients, records, files, team accounts and the family accounts that only belonged to that center.', 'la dirección puede solicitar el cierre del centro. Se eliminan todos sus datos: pacientes, registros, archivos, cuentas del equipo y las cuentas de familias que solo pertenecían a ese centro.')],
          [L('Artificial intelligence:', 'Inteligencia artificial:'), L('you can stop sending data to the AI provider at any time by turning off the AI features. The provider does not keep the requests (zero data retention), so there is nothing to delete there.', 'puedes dejar de enviar datos al proveedor de IA en cualquier momento desactivando las funciones de IA. El proveedor no conserva las consultas (retención cero), así que allí no queda nada que eliminar.')],
        ]} />
      </>,
    },
    {
      id: 'terceros', Icon: LogIn, title: L('Google and Microsoft services', 'Servicios de Google y Microsoft'),
      body: <>
        <p>{L('If you sign in with Google or Microsoft, we only receive your name, email address and profile photo to create and manage your account. We do not access your email, files or other services.',
          'Si inicias sesión con Google o Microsoft, solo recibimos tu nombre, correo electrónico y fotografía de perfil para crear y gestionar tu cuenta. No accedemos a tu correo, archivos ni a otros servicios.')}</p>
        <p>{L('If you link Google Calendar or Outlook Calendar, access is limited to creating, updating and deleting the events of your appointments. We do not read, store or analyze the other events in your calendar. You may revoke it at any time from My profile → Linked calendars.',
          'Si vinculas Google Calendar u Outlook Calendar, el acceso se limita a crear, actualizar y eliminar los eventos de tus citas. No leemos, guardamos ni analizamos los demás eventos de tu calendario. Puedes revocarlo en cualquier momento desde Mi perfil → Calendarios vinculados.')}</p>
        <p>{L("Vanty ABA's use and transfer to any other app of information received from Google APIs will adhere to the ",
          'El uso que Vanty ABA hace de la información recibida de las APIs de Google, y su transferencia a cualquier otra aplicación, se ajustará a la ')}
          <a href="https://developers.google.com/terms/api-services-user-data-policy" target="_blank" rel="noopener noreferrer" className="font-semibold text-v-accent hover:underline">
            {L('Google API Services User Data Policy', 'Política de Datos de Usuario de los Servicios de API de Google')}
          </a>
          {L(', including the Limited Use requirements.', ', incluidos los requisitos de Uso Limitado (Limited Use).')}</p>
        <p>{L('Data received from Google APIs is not sent to artificial intelligence services and is not used to develop, improve or train generalized AI or machine learning models.',
          'Los datos recibidos de las APIs de Google no se envían a servicios de inteligencia artificial ni se usan para desarrollar, mejorar o entrenar modelos generales de inteligencia artificial o aprendizaje automático.')}</p>
      </>,
    },
    {
      id: 'conservacion', Icon: Archive, title: L('Data retention', 'Conservación de los datos'),
      body: <p>{L('Clinical information is kept while care is active and, afterwards, for the minimum period required by applicable health regulations on clinical records. Once that period ends, it is securely deleted or anonymized. Account data is deleted when the account is closed, except where the law requires otherwise.',
        'La información clínica se conserva mientras la atención esté activa y, posteriormente, durante el plazo mínimo que exige la normativa sanitaria aplicable a las historias clínicas. Vencido dicho plazo, se elimina o anonimiza de forma segura. Los datos de cuenta se eliminan al cerrarse la cuenta, salvo que la ley disponga lo contrario.')}</p>,
    },
    {
      id: 'cambios', Icon: RefreshCw, title: L('Changes to this policy', 'Cambios en esta política'),
      body: <p>{L('We may update this policy to reflect improvements to the service or regulatory changes. Relevant changes will be communicated through a notice within the platform, and the date of the last update will always appear at the top of this document.',
        'Podemos actualizar esta política para reflejar mejoras en el servicio o cambios normativos. Los cambios relevantes se comunicarán mediante un aviso dentro de la plataforma, y la fecha de la última actualización figurará siempre al inicio de este documento.')}</p>,
    },
    {
      id: 'contacto', Icon: Mail, title: L('Contact', 'Contacto'),
      body: <p>{L(`For questions about the processing of your data, contact the center that provides your care through the channels available in the platform. For matters related to the ${P} platform, you may write to us through the support section or at vantysupport@gmail.com.`,
        `Para consultas sobre el tratamiento de tus datos, comunícate con el centro que te atiende a través de los canales disponibles en la plataforma. Para asuntos relacionados con la plataforma ${P}, puedes escribirnos desde la sección de soporte o a vantysupport@gmail.com.`)}</p>,
    },
  ]
}

export default async function PrivacidadPage() {
  const en = (await cookies()).get('vanty_locale')?.value === 'en'
  const L = (e: string, s: string) => (en ? e : s)
  return (
    <LegalPage
      en={en}
      EyebrowIcon={ShieldCheck}
      titleA={L('Privacy ', 'Política de ')}
      titleB={L('Policy', 'Privacidad')}
      intro={L(`At ${P} we understand that we handle especially sensitive information: the health data of children and their families. This policy explains, clearly and transparently, what information we process, why we do it and how we protect it.`,
        `En ${P} entendemos que gestionamos información especialmente sensible: los datos de salud de niñas, niños y sus familias. Esta política explica, de forma clara y transparente, qué información tratamos, para qué lo hacemos y cómo la protegemos.`)}
      sellos={[[KeyRound, L('AES-256 encryption', 'Cifrado AES-256')], [Lock, 'TLS'], [ServerCog, 'Row Level Security'], [BadgeCheck, L('Law No. 29733 (Peru)', 'Ley N.º 29733')]]}
      updated={L('Last updated: September 2026', 'Última actualización: septiembre de 2026')}
      resumen={{
        titulo: L('At a glance', 'En resumen'),
        items: [
          [Lock, L('Protected data', 'Datos protegidos'), L('Encrypted at rest and in transit, isolated by center.', 'Cifrados en reposo y en tránsito, aislados por centro.')],
          [Ban, L('We never sell your data', 'Nunca vendemos tus datos'), L('No advertising or commercial profiling.', 'Sin publicidad ni perfiles comerciales.')],
          [Sparkles, L('AI only with permission', 'IA solo con permiso'), L('Off until the center authorizes it; not used to train models.', 'Desactivada hasta que el centro la autoriza; no se usa para entrenar modelos.')],
          [UserCheck, L('You stay in control', 'Tú tienes el control'), L('Access, rectify or delete your information.', 'Accede, corrige o elimina tu información.')],
        ],
      }}
      secciones={secciones(en)}
      otro={{ href: '/terminos', label: L('Terms of Service', 'Términos de servicio') }}
    />
  )
}
