// lib/lang.ts — Helper central de idioma para prompts de IA
// Importar en cualquier route.ts: import { getLangInstruction, getLocaleFromRequest } from '@/lib/lang'

export type Locale = 'es' | 'en'

/**
 * Lee el locale del request (body.locale > header x-locale > 'es')
 */
export function getLocaleFromRequest(request: Request, body?: any): Locale {
  const fromBody = body?.locale
  const fromHeader = request.headers.get('x-locale')
  const raw = String(fromBody || fromHeader || 'es').toLowerCase()
  return raw.startsWith('en') ? 'en' : 'es'
}

/**
 * Devuelve la instrucción de idioma para añadir al system prompt de la IA.
 * Si locale es 'en', fuerza respuesta en inglés profesional.
 * Si locale es 'es' o no especificado, no añade nada (comportamiento por defecto).
 */
export function getLangInstruction(locale: string): string {
  const en = String(locale || '').toLowerCase().startsWith('en')
  const lang = en
    ? '\n\n🌐 LANGUAGE — MANDATORY: Respond ENTIRELY in professional clinical English. Every part of your output — headings, labels, section titles, terminology, summaries and recommendations — must be in English. Do NOT reply in Spanish.'
    : ''
  const src = en
    ? '\n\n🔒 SOURCES — MANDATORY: Base your clinical reasoning on established evidence-based ABA practice, but present it entirely as your OWN professional clinical judgment. NEVER name, cite, quote or reference any external standardized assessment instrument, test or curriculum (or its item codes / section letters) in your response, even if such material appears in the context provided to you. Describe every objective, criterion and recommendation in your own words.'
    : '\n\n🔒 FUENTES — OBLIGATORIO: Fundamenta tu razonamiento en buenas prácticas ABA basadas en evidencia, pero preséntalo enteramente como tu PROPIO juicio clínico profesional. NUNCA nombres, cites, transcribas ni hagas referencia a instrumentos de evaluación estandarizados, tests o currículos de terceros (ni a sus códigos de ítem o letras de sección) en tu respuesta, aunque ese material aparezca en el contexto que se te entrega. Describe cada objetivo, criterio y recomendación con tus propias palabras.'
  return lang + src
}

/**
 * Para documentos generados (DOCX): devuelve labels en el idioma correcto
 */
export function getDocLabels(locale: Locale) {
  if (locale === 'en') {
    return {
      patient: 'PATIENT',
      age: 'AGE',
      reportDate: 'REPORT DATE',
      evaluationType: 'EVALUATION TYPE',
      ageUnit: 'years',
      notSpecified: 'Not specified',
      footer: 'This report was generated with the support of clinical artificial intelligence (ARIA - SANTI). It must be reviewed and signed by the responsible professional before delivery.',
      generated: 'Generated by SANTI — Neuropsychological Clinical Management System  |  Page ',
      of: ' of ',
    }
  }
  return {
    patient: 'PACIENTE',
    age: 'EDAD',
    reportDate: 'FECHA DEL INFORME',
    evaluationType: 'TIPO DE EVALUACIÓN',
    ageUnit: 'años',
    notSpecified: 'No especificada',
    footer: 'Este informe fue generado con el apoyo de inteligencia artificial clínica (ARIA - SANTI). Debe ser revisado y firmado por el profesional responsable antes de su entrega.',
    generated: 'Generado por SANTI — Sistema de Gestión Clínica Neuropsicológica  |  Página ',
    of: ' de ',
  }
}
